language: minimal

services:
  - docker

install:
  - bash .build_travis.sh

script:
  - cd dockerhome
  - git clone "https://$FLOWVR_USER:$FLOWVR_PASSWORD@gitlab.inria.fr/flowvr/flowvr-ex.git"
  - cd flowvr-ex
  - git checkout dev
  - cd ..
  - git clone "https://github.com/xy124/parflow.git"
  - cd parflow
  - git checkout parFlowVR
  - cd ../..
  - ./run.sh test

deploy:
  provider: script
  script: "./deploy_docker.sh"
  on:
    branch: master
